"""Built-in profile and runtime defaults."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ProfilePreset:
    name: str
    audience: str
    genre: str
    section: str
    register: str
    active_rules: tuple[str, ...]
    rule_overrides: dict[str, dict[str, object]] = field(default_factory=dict)


DEFAULT_PROFILE = "research"

PROFILE_PRESETS: dict[str, ProfilePreset] = {
    "research": ProfilePreset(
        name="research",
        audience="specialist",
        genre="research_note",
        section="body",
        register="formal",
        active_rules=(
            "surface.sentence_length",
            "surface.passive_voice",
            "surface.contraction",
            "surface.nominalization",
            "surface.stacked_nominalization_chain",
            "surface.abstract_framing",
            "surface.vague_procedural_nominalization",
            "surface.concrete_subject",
            "surface.abstract_compound_modifier",
            "surface.assumption_hypothesis_framing",
            "surface.prep_chain",
            "surface.noun_cluster",
            "surface.banned_transition",
            "surface.personal_pronoun",
            "surface.generic_one",
            "surface.bare_pronoun_opening",
            "surface.verbose_preamble",
            "surface.redundant_leadin",
            "surface.long_inline_enumeration",
            "surface.vague_phrasing",
            "surface.indefinite_reference",
            "surface.case_scaffolding",
            "surface.numbered_case",
            "surface.cross_reference",
            "surface.heading_link",
            "surface.see_link",
            "surface.raw_anchor",
            "surface.generic_link_text",
            "discourse.subject_verb_distance",
            "discourse.subordinate_clause",
            "discourse.stress_position",
            "discourse.transition_quality",
            "discourse.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.prose_outside_heading",
            "audience.acronym_burden",
            "audience.definition_before_use",
            "audience.jargon_density",
            "audience.claim_calibration",
            "audience.qualitative_claim_without_quant_support",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
        ),
        rule_overrides={
            "surface.sentence_length": {"options": {"max_words": 32}},
            "discourse.subject_verb_distance": {"options": {"max_distance": 10}},
            "paragraph.paragraph_redundancy": {"options": {"min_similarity": 0.9}},
        },
    ),
    "pedagogical": ProfilePreset(
        name="pedagogical",
        audience="learner",
        genre="lecture_note",
        section="body",
        register="pedagogical",
        active_rules=(
            "surface.sentence_length",
            "surface.passive_voice",
            "surface.contraction",
            "surface.nominalization",
            "surface.stacked_nominalization_chain",
            "surface.abstract_framing",
            "surface.vague_procedural_nominalization",
            "surface.concrete_subject",
            "surface.abstract_compound_modifier",
            "surface.assumption_hypothesis_framing",
            "surface.prep_chain",
            "surface.noun_cluster",
            "surface.banned_transition",
            "surface.personal_pronoun",
            "surface.generic_one",
            "surface.bare_pronoun_opening",
            "surface.verbose_preamble",
            "surface.redundant_leadin",
            "surface.long_inline_enumeration",
            "surface.vague_phrasing",
            "surface.indefinite_reference",
            "surface.case_scaffolding",
            "surface.numbered_case",
            "surface.cross_reference",
            "surface.heading_link",
            "surface.see_link",
            "surface.raw_anchor",
            "surface.generic_link_text",
            "discourse.subject_verb_distance",
            "discourse.subordinate_clause",
            "discourse.stress_position",
            "discourse.transition_quality",
            "discourse.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.prose_outside_heading",
            "audience.acronym_burden",
            "audience.definition_before_use",
            "audience.jargon_density",
            "audience.claim_calibration",
            "audience.qualitative_claim_without_quant_support",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
        ),
        rule_overrides={
            "surface.sentence_length": {"options": {"max_words": 24}},
            "discourse.subject_verb_distance": {"options": {"max_distance": 6}},
            "paragraph.topic_sentence": {"options": {"minimum_score": 0.55}},
            "audience.jargon_density": {"options": {"max_density": 0.1}},
        },
    ),
    "math": ProfilePreset(
        name="math",
        audience="specialist",
        genre="mathematical_note",
        section="body",
        register="mathematical",
        active_rules=(
            "surface.sentence_length",
            "surface.passive_voice",
            "surface.nominalization",
            "surface.stacked_nominalization_chain",
            "surface.abstract_framing",
            "surface.vague_procedural_nominalization",
            "surface.concrete_subject",
            "surface.abstract_compound_modifier",
            "surface.assumption_hypothesis_framing",
            "surface.prep_chain",
            "surface.noun_cluster",
            "surface.banned_transition",
            "surface.personal_pronoun",
            "surface.generic_one",
            "surface.bare_pronoun_opening",
            "surface.verbose_preamble",
            "surface.redundant_leadin",
            "surface.long_inline_enumeration",
            "surface.vague_phrasing",
            "surface.indefinite_reference",
            "surface.case_scaffolding",
            "surface.numbered_case",
            "surface.cross_reference",
            "surface.heading_link",
            "surface.see_link",
            "surface.raw_anchor",
            "surface.generic_link_text",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
            "discourse.subject_verb_distance",
            "discourse.subordinate_clause",
            "discourse.stress_position",
            "discourse.transition_quality",
            "discourse.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.prose_outside_heading",
            "audience.acronym_burden",
            "audience.definition_before_use",
            "audience.jargon_density",
            "audience.claim_calibration",
            "audience.qualitative_claim_without_quant_support",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
        ),
        rule_overrides={
            "surface.sentence_length": {"options": {"max_words": 26}},
            "math.display_math": {"options": {"require_leadin": True}},
            "audience.claim_calibration": {"options": {"lookback_sentences": 4}},
            "audience.jargon_density": {"options": {"max_density": 0.22}},
        },
    ),
}
