"""Built-in profile and runtime defaults."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ProfilePreset:
    """Profilepreset."""

    name: str
    audience: str
    genre: str
    section: str
    register: str
    active_rules: tuple[str, ...]
    rule_overrides: dict[str, dict[str, object]] = field(default_factory=dict)


DEFAULT_PROFILE = "research"

PROFILE_PRESETS: dict[str, ProfilePreset] = {
    "research": ProfilePreset(
        name="research",
        audience="specialist",
        genre="research_note",
        section="body",
        register="formal",
        active_rules=(
            "syntax.sentence_length",
            "syntax.passive_voice",
            "vocabulary.contraction",
            "vocabulary.nominalization",
            "vocabulary.stacked_nominalization_chain",
            "vocabulary.abstract_framing",
            "vocabulary.vague_procedural_nominalization",
            "vocabulary.concrete_subject",
            "vocabulary.abstract_compound_modifier",
            "vocabulary.assumption_hypothesis_framing",
            "vocabulary.prep_chain",
            "vocabulary.noun_cluster",
            "linkage.banned_transition",
            "reference.personal_pronoun",
            "reference.generic_one",
            "reference.bare_pronoun_opening",
            "vocabulary.verbose_preamble",
            "vocabulary.redundant_leadin",
            "syntax.long_inline_enumeration",
            "vocabulary.vague_phrasing",
            "vocabulary.double_negative",
            "vocabulary.boilerplate_opener",
            "vocabulary.indefinite_reference",
            "vocabulary.filler_noun_scaffolding",
            "vocabulary.cardinality_framing",
            "linkage.case_scaffolding",
            "linkage.numbered_case",
            "reference.cross_reference",
            "reference.structural_metalanguage",
            "reference.citation_as_agent",
            "reference.citation_tail_parenthetical",
            "reference.heading_link",
            "reference.see_link",
            "reference.raw_anchor",
            "reference.generic_link_text",
            "syntax.subject_verb_distance",
            "syntax.subordinate_clause",
            "syntax.embedding_depth",
            "syntax.multi_action_sentence",
            "linkage.stress_position",
            "linkage.transition_quality",
            "linkage.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.declarative_heading",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_order_sequence",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.opening_message_focus",
            "structure.orphan_section",
            "structure.prose_outside_heading",
            "terminology.acronym_burden",
            "terminology.definition_before_use",
            "terminology.jargon_density",
            "evidence.claim_calibration",
            "evidence.qualitative_claim_without_quant_support",
            "evidence.imprecise_quantifier_without_citation",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
        ),
        rule_overrides={
            "syntax.sentence_length": {"options": {"max_words": 34}},
            "syntax.subject_verb_distance": {"options": {"max_distance": 10}},
            "syntax.passive_voice": {
                "options": {"min_topic_overlap_for_passive_exemption": 0.18}
            },
            "syntax.embedding_depth": {
                "options": {"max_dependency_depth": 6, "max_embedding_markers": 5}
            },
            "syntax.multi_action_sentence": {"options": {"max_load_bearing_verbs": 2}},
            "linkage.transition_quality": {
                "options": {
                    "min_overlap_without_connector": 0.15,
                    "max_shift_findings": 2,
                    "min_average_overlap_without_connectors": 0.3,
                    "max_implicit_contrast_findings": 2,
                    "min_overlap_for_implicit_contrast": 0.28,
                }
            },
            "paragraph.paragraph_redundancy": {"options": {"min_similarity": 0.9}},
            "paragraph.topic_sentence": {"options": {"minimum_score": 0.42}},
        },
    ),
    "strict": ProfilePreset(
        name="strict",
        audience="specialist",
        genre="technical_note",
        section="body",
        register="strict",
        active_rules=(
            "syntax.sentence_length",
            "syntax.passive_voice",
            "vocabulary.contraction",
            "vocabulary.nominalization",
            "vocabulary.stacked_nominalization_chain",
            "vocabulary.abstract_framing",
            "vocabulary.vague_procedural_nominalization",
            "vocabulary.concrete_subject",
            "vocabulary.abstract_compound_modifier",
            "vocabulary.assumption_hypothesis_framing",
            "vocabulary.prep_chain",
            "vocabulary.noun_cluster",
            "linkage.banned_transition",
            "reference.personal_pronoun",
            "reference.generic_one",
            "reference.bare_pronoun_opening",
            "vocabulary.verbose_preamble",
            "vocabulary.redundant_leadin",
            "syntax.long_inline_enumeration",
            "vocabulary.vague_phrasing",
            "vocabulary.double_negative",
            "vocabulary.boilerplate_opener",
            "vocabulary.indefinite_reference",
            "vocabulary.filler_noun_scaffolding",
            "vocabulary.cardinality_framing",
            "linkage.case_scaffolding",
            "linkage.numbered_case",
            "reference.cross_reference",
            "reference.structural_metalanguage",
            "reference.citation_as_agent",
            "reference.citation_tail_parenthetical",
            "reference.heading_link",
            "reference.see_link",
            "reference.raw_anchor",
            "reference.generic_link_text",
            "syntax.subject_verb_distance",
            "syntax.subordinate_clause",
            "syntax.embedding_depth",
            "syntax.multi_action_sentence",
            "linkage.stress_position",
            "linkage.transition_quality",
            "linkage.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.declarative_heading",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_order_sequence",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.opening_message_focus",
            "structure.orphan_section",
            "structure.prose_outside_heading",
            "terminology.acronym_burden",
            "terminology.definition_before_use",
            "terminology.jargon_density",
            "evidence.claim_calibration",
            "evidence.qualitative_claim_without_quant_support",
            "evidence.imprecise_quantifier_without_citation",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
        ),
        rule_overrides={
            "syntax.sentence_length": {"options": {"max_words": 22}},
            "syntax.subject_verb_distance": {"options": {"max_distance": 5}},
            "syntax.passive_voice": {
                "options": {"min_topic_overlap_for_passive_exemption": 0.3}
            },
            "syntax.embedding_depth": {
                "options": {"max_dependency_depth": 5, "max_embedding_markers": 4}
            },
            "syntax.multi_action_sentence": {"options": {"max_load_bearing_verbs": 1}},
            "syntax.long_inline_enumeration": {"options": {"max_items": 3}},
            "linkage.transition_quality": {
                "options": {
                    "min_overlap_without_connector": 0.22,
                    "max_shift_findings": 4,
                    "min_average_overlap_without_connectors": 0.45,
                    "max_implicit_contrast_findings": 4,
                    "min_overlap_for_implicit_contrast": 0.16,
                }
            },
            "paragraph.topic_sentence": {"options": {"minimum_score": 0.56}},
            "paragraph.paragraph_redundancy": {"options": {"min_similarity": 0.86}},
            "terminology.jargon_density": {"options": {"max_density": 0.08}},
        },
    ),
    "pedagogical": ProfilePreset(
        name="pedagogical",
        audience="learner",
        genre="lecture_note",
        section="body",
        register="pedagogical",
        active_rules=(
            "syntax.sentence_length",
            "syntax.passive_voice",
            "vocabulary.contraction",
            "vocabulary.nominalization",
            "vocabulary.stacked_nominalization_chain",
            "vocabulary.abstract_framing",
            "vocabulary.vague_procedural_nominalization",
            "vocabulary.concrete_subject",
            "vocabulary.abstract_compound_modifier",
            "vocabulary.assumption_hypothesis_framing",
            "vocabulary.prep_chain",
            "vocabulary.noun_cluster",
            "linkage.banned_transition",
            "reference.personal_pronoun",
            "reference.generic_one",
            "reference.bare_pronoun_opening",
            "vocabulary.verbose_preamble",
            "vocabulary.redundant_leadin",
            "syntax.long_inline_enumeration",
            "vocabulary.vague_phrasing",
            "vocabulary.double_negative",
            "vocabulary.boilerplate_opener",
            "vocabulary.indefinite_reference",
            "vocabulary.filler_noun_scaffolding",
            "vocabulary.cardinality_framing",
            "linkage.case_scaffolding",
            "linkage.numbered_case",
            "reference.cross_reference",
            "reference.structural_metalanguage",
            "reference.citation_as_agent",
            "reference.citation_tail_parenthetical",
            "reference.heading_link",
            "reference.see_link",
            "reference.raw_anchor",
            "reference.generic_link_text",
            "syntax.subject_verb_distance",
            "syntax.subordinate_clause",
            "syntax.embedding_depth",
            "syntax.multi_action_sentence",
            "linkage.stress_position",
            "linkage.transition_quality",
            "linkage.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.declarative_heading",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_order_sequence",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.opening_message_focus",
            "structure.orphan_section",
            "structure.prose_outside_heading",
            "terminology.acronym_burden",
            "terminology.definition_before_use",
            "terminology.jargon_density",
            "evidence.claim_calibration",
            "evidence.qualitative_claim_without_quant_support",
            "evidence.imprecise_quantifier_without_citation",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
        ),
        rule_overrides={
            "syntax.sentence_length": {"options": {"max_words": 22}},
            "syntax.subject_verb_distance": {"options": {"max_distance": 5}},
            "syntax.embedding_depth": {
                "options": {"max_dependency_depth": 5, "max_embedding_markers": 4}
            },
            "syntax.multi_action_sentence": {"options": {"max_load_bearing_verbs": 1}},
            "linkage.transition_quality": {
                "options": {
                    "min_overlap_without_connector": 0.2,
                    "max_shift_findings": 4,
                    "min_average_overlap_without_connectors": 0.4,
                    "max_implicit_contrast_findings": 4,
                    "min_overlap_for_implicit_contrast": 0.18,
                }
            },
            "paragraph.topic_sentence": {"options": {"minimum_score": 0.52}},
            "terminology.jargon_density": {"options": {"max_density": 0.08}},
        },
    ),
    "math": ProfilePreset(
        name="math",
        audience="specialist",
        genre="mathematical_note",
        section="body",
        register="mathematical",
        active_rules=(
            "syntax.sentence_length",
            "syntax.passive_voice",
            "vocabulary.nominalization",
            "vocabulary.stacked_nominalization_chain",
            "vocabulary.abstract_framing",
            "vocabulary.vague_procedural_nominalization",
            "vocabulary.concrete_subject",
            "vocabulary.abstract_compound_modifier",
            "vocabulary.assumption_hypothesis_framing",
            "vocabulary.prep_chain",
            "vocabulary.noun_cluster",
            "linkage.banned_transition",
            "reference.personal_pronoun",
            "reference.generic_one",
            "reference.bare_pronoun_opening",
            "vocabulary.verbose_preamble",
            "vocabulary.redundant_leadin",
            "syntax.long_inline_enumeration",
            "vocabulary.vague_phrasing",
            "vocabulary.double_negative",
            "vocabulary.boilerplate_opener",
            "vocabulary.indefinite_reference",
            "vocabulary.filler_noun_scaffolding",
            "vocabulary.cardinality_framing",
            "linkage.case_scaffolding",
            "linkage.numbered_case",
            "reference.cross_reference",
            "reference.structural_metalanguage",
            "reference.citation_as_agent",
            "reference.citation_tail_parenthetical",
            "reference.heading_link",
            "reference.see_link",
            "reference.raw_anchor",
            "reference.generic_link_text",
            "math.inline_math",
            "math.display_math",
            "math.display_ambiguous",
            "math.display_unclosed",
            "math.bare_symbol",
            "math.shorthand",
            "math.imperative_opening",
            "math.prose_math",
            "math.proof_marker",
            "syntax.subject_verb_distance",
            "syntax.subordinate_clause",
            "syntax.embedding_depth",
            "syntax.multi_action_sentence",
            "linkage.stress_position",
            "linkage.transition_quality",
            "linkage.semicolon_connector",
            "paragraph.topic_sentence",
            "paragraph.parallelism",
            "paragraph.inline_enumeration_overload",
            "paragraph.inline_case_split",
            "paragraph.double_framing",
            "paragraph.lexical_repetition",
            "paragraph.concept_reference_drift",
            "paragraph.reformulation_inflation",
            "paragraph.sentence_redundancy",
            "paragraph.paragraph_redundancy",
            "structure.heading_parallelism",
            "structure.heading_capitalization",
            "structure.declarative_heading",
            "structure.heading_level_skip",
            "structure.section_balance",
            "structure.section_order_sequence",
            "structure.section_opener_block_kind",
            "structure.opening_sentence_presence",
            "structure.opening_message_focus",
            "structure.orphan_section",
            "structure.prose_outside_heading",
            "terminology.acronym_burden",
            "terminology.definition_before_use",
            "terminology.jargon_density",
            "evidence.claim_calibration",
            "evidence.qualitative_claim_without_quant_support",
            "evidence.imprecise_quantifier_without_citation",
            "math.assumption_motivation_order",
            "math.proof_placement_context",
            "math.display_followup_interpretation",
            "math.consecutive_display_blocks_without_bridge",
        ),
        rule_overrides={
            "syntax.sentence_length": {"options": {"max_words": 30}},
            "syntax.subject_verb_distance": {"options": {"max_distance": 11}},
            "syntax.passive_voice": {
                "options": {"min_topic_overlap_for_passive_exemption": 0.16}
            },
            "syntax.embedding_depth": {
                "options": {"max_dependency_depth": 6, "max_embedding_markers": 5}
            },
            "syntax.multi_action_sentence": {"options": {"max_load_bearing_verbs": 2}},
            "linkage.transition_quality": {
                "options": {
                    "min_overlap_without_connector": 0.15,
                    "max_shift_findings": 2,
                    "min_average_overlap_without_connectors": 0.3,
                    "max_implicit_contrast_findings": 2,
                    "min_overlap_for_implicit_contrast": 0.28,
                }
            },
            "paragraph.topic_sentence": {"options": {"minimum_score": 0.42}},
            "math.display_math": {"options": {"require_leadin": True}},
            "evidence.claim_calibration": {"options": {"lookback_sentences": 4}},
            "terminology.jargon_density": {"options": {"max_density": 0.25}},
        },
    ),
}
